export const FETCH_CHAT_HISTORY = 'FETCH_CHAT_HISTORY';
export const FETCH_CHAT_HISTORY_SUCCESS = 'FETCH_CHAT_HISTORY_SUCCESS';
export const FETCH_CHAT_HISTORY_FAILURE = 'FETCH_CHAT_HISTORY_FAILURE';

export const SEND_MESSAGE = 'SEND_MESSAGE';
export const SEND_MESSAGE_SUCCESS = 'SEND_MESSAGE_SUCCESS';
export const SEND_MESSAGE_FAILURE = 'SEND_MESSAGE_FAILURE';
