// src/Store/Twit/ActionTypes.js
export const TWEET_CREATE_REQUEST = "TWEET_CREATE_REQUEST";
export const TWEET_CREATE_SUCCESS = "TWEET_CREATE_SUCCESS";
export const TWEET_CREATE_FAILURE = "TWEET_CREATE_FAILURE";


export const FETCH_COMMENTS_SUCCESS = 'FETCH_COMMENTS_SUCCESS';
export const ADD_COMMENT_SUCCESS = 'ADD_COMMENT_SUCCESS';

export const TWEET_DELETE_REQUEST = "TWEET_DELETE_REQUEST";
export const TWEET_DELETE_SUCCESS = "TWEET_DELETE_SUCCESS";
export const TWEET_DELETE_FAILURE = "TWEET_DELETE_FAILURE";

export const SUBSCRIBE_USER_REQUEST = 'SUBSCRIBE_USER_REQUEST';
export const SUBSCRIBE_USER_SUCCESS = 'SUBSCRIBE_USER_SUCCESS';
export const SUBSCRIBE_USER_FAILURE = 'SUBSCRIBE_USER_FAILURE';

export const GET_ALL_TWEETS_REQUEST = "GET_ALL_TWEETS_REQUEST";
export const GET_ALL_TWEETS_SUCCESS = "GET_ALL_TWEETS_SUCCESS";
export const GET_ALL_TWEETS_FAILURE = "GET_ALL_TWEETS_FAILURE";

export const GET_USERS_TWEET_REQUEST = "GET_USERS_TWEET_REQUEST";
export const GET_USERS_TWEET_SUCCESS = "GET_USERS_TWEET_SUCCESS";
export const GET_USERS_TWEET_FAILURE = "GET_USERS_TWEET_FAILURE";

export const USER_LIKE_TWEET_REQUEST = "USER_LIKE_TWEET_REQUEST";
export const USER_LIKE_TWEET_SUCCESS = "USER_LIKE_TWEET_SUCCESS";
export const USER_LIKE_TWEET_FAILURE = "USER_LIKE_TWEET_FAILURE";

export const LIKE_TWEET_REQUEST = "LIKE_TWEET_REQUEST";
export const LIKE_TWEET_SUCCESS = "LIKE_TWEET_SUCCESS";
export const LIKE_TWEET_FAILURE = "LIKE_TWEET_FAILURE";

export const FIND_TWEET_BY_ID_REQUEST = "FIND_TWEET_BY_ID_REQUEST";
export const FIND_TWEET_BY_ID_SUCCESS = "FIND_TWEET_BY_ID_SUCCESS";
export const FIND_TWEET_BY_ID_FAILURE = "FIND_TWEET_BY_ID_FAILURE";

export const REPLY_TWEET_REQUEST = "REPLY_TWEET_REQUEST";
export const REPLY_TWEET_SUCCESS = "REPLY_TWEET_SUCCESS";
export const REPLY_TWEET_FAILURE = "REPLY_TWEET_FAILURE";

export const RTWEET_REQUEST = "RTWEET_REQUEST";
export const RTWEET_SUCCESS = "RTWEET_SUCCESS";
export const RTWEET_FAILURE = "RTWEET_FAILURE";

export const ADD_COMMENT = 'ADD_COMMENT';
export const LIKE_COMMENT = 'LIKE_COMMENT';

export const GET_TWITS_REQUEST = "GET_TWITS_REQUEST";
export const GET_TWITS_SUCCESS = "GET_TWITS_SUCCESS";
export const GET_TWITS_FAILURE = "GET_TWITS_FAILURE";